[project]
name = "fastapi-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "boto3>=1.42.39",
  "boto3-stubs[s3]>=1.42.60",
  "fastapi[standard]>=0.128.0",
  "langchain-community>=0.4.1",
  "langchain-groq>=1.1.2",
  "langchain-huggingface>=1.2.0",
  "langchain-ollama>=1.0.1",
  "langchain-qdrant>=1.1.0",
  "langchain-text-splitters>=1.1.0",
  "pandas>=3.0.0",
  "pillow>=12.1.0",
  "pymongo>=4.16.0",
  "pymupdf>=1.26.7",
  "qdrant-client>=1.16.2",
  "sentence-transformers>=5.2.2",
  "supabase>=2.27.2",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
